name: Leaning GitHub Actions
run-name: I'm learning GitHub Actions!
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Define variable
      run: echo "USERNAME= ${{ github.actor }}" >> $GITHUB_ENV
    - name: Run Script
      run: node index.js 


